# PostgreSQL. Versions 10 and up are supported. 

development:
  adapter: postgresql
  encoding: unicode
  database: task_track_ap-api_development
  pool: 5
  username: postgres
  password: 1234
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: task_track_ap-api_test
  pool: 5
  username: postgres
  password: 1234
  timeout: 5000

